AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CognitoDomain:
    Type: String
    MinLength: 3
    MaxLength: 63
  HostedZoneId:
    Description: Hosted Zone ID
    Type: String
  EmailSourceArn:
    Description: Email Source ARN
    Type: String
  CertificateArn:
    Description: Certificate ARN
    Type: String
  UserPoolName:
    Type: String
    Default: TekCapsuleUserPool
    Description: Name of the Amazon Cognito User Pool
  UserPoolClientName:
    Type: String
    Default: TekCapsuleUserPoolClient
    Description: Name of the Amazon Cognito User Pool Client
  IdentityPoolName:
    Type: String
    Default: TekCapsuleIdentityPool
    Description: Name of the Amazon Cognito Identity Pool
  IdentityPoolRoleName:
    Type: String
    Default: TekCapsuleIdentityPoolRole
    Description: Name of the AWS Identity and Access Management IAM role for the identity
      pool

Resources:

  CertificateManagerCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref CognitoDomain
      SubjectAlternativeNames:
        - !Sub "www.${CognitoDomain}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref CognitoDomain
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${CognitoDomain}"
          HostedZoneId: !Ref HostedZoneId

  TekCapsuleCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Ref: UserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false

  TekCapsuleCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: TekCapsuleCognitoUserPool
      ClientName:
        Ref: UserPoolClientName
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      CallbackURLs:
        - https://dev.tekcapsule.com/
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - profile
        - openid

  TekCapsuleUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: tekcapsule
      UserPoolId:
        Ref: TekCapsuleCognitoUserPool


Outputs:
  CognitoUserPoolID:
    Value: !Ref UserPoolName
    Description: The UserPool ID
  CognitoAppClientID:
    Value: !Ref UserPoolClientName
    Description: TekCapsule Web Client
  HostedUIURL:
    Value: !Sub https://${CognitoDomain}.auth.us-west-2.amazoncognito.com/login?client_id=${UserPoolClientName}&response_type=code&scope=email+openid+phone+profile&redirect_uri=https://dev.tekcapsule.com
    Description: The hosted UI URL